"use client";
import {FileSpreadsheet,Play,UploadCloud,X} from "lucide-react";
import {useRouter} from "next/navigation";
import {type DragEvent,useRef,useState} from "react";
import {UpgradeBanner} from "@/components/upgrade-banner";
import {asError} from "@/lib/errors";
import {uploadFile} from "@/lib/upload-file";
type Kind="invoices"|"payments";
function Dropzone({kind,file,onFile}:{kind:Kind;file:File|null;onFile:(file:File|null)=>void}){const input=useRef<HTMLInputElement>(null),title=kind==="invoices"?"Invoices CSV":"Bank or payout CSV";function drop(event:DragEvent){event.preventDefault();onFile(event.dataTransfer.files[0]??null)}return <div className={`dropzone card ${file?"has-file":""}`} onDragOver={event=>event.preventDefault()} onDrop={drop}><input ref={input} hidden type="file" accept=".csv,text/csv" onChange={event=>onFile(event.target.files?.[0]??null)}/>{file?<><FileSpreadsheet size={30}/><div><strong>{file.name}</strong><span>{(file.size/1024).toFixed(1)} KB</span></div><button className="icon-button" aria-label={`Remove ${title}`} onClick={()=>onFile(null)}><X size={17}/></button></>:<><UploadCloud size={30}/><h2>{title}</h2><p>Drop a CSV here, or choose a file.</p><button className="button secondary" onClick={()=>input.current?.click()}>Choose CSV</button></>}</div>}
export default function NewRunPage(){const router=useRouter(),[invoices,setInvoices]=useState<File|null>(null),[payments,setPayments]=useState<File|null>(null),[daysBefore,setDaysBefore]=useState(7),[daysAfter,setDaysAfter]=useState(14),[busy,setBusy]=useState(false),[error,setError]=useState(""),[planLimit,setPlanLimit]=useState(false);async function run(){if(!invoices||!payments)return;setBusy(true);setError("");setPlanLimit(false);try{const invoiceUpload=await uploadFile("invoices",invoices);const paymentUpload=await uploadFile("payments",payments),response=await fetch("/api/match-runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invoiceUploadId:invoiceUpload.id,paymentUploadId:paymentUpload.id,settings:{dateWindowDaysBefore:daysBefore,dateWindowDaysAfter:daysAfter}})}),data=await response.json().catch(()=>({}));if(response.status===402&&data.code==="PLAN_LIMIT"){setPlanLimit(true);return}if(!response.ok)throw new Error(data.error??"Could not run matcher");router.push(`/app/runs/${data.id}`)}catch(value){setError(asError(value,"Could not run matcher").message)}finally{setBusy(false)}}return <main className="page narrow"><div className="page-head"><div><p className="eyebrow">New reconciliation</p><h1>Bring the two sides together</h1><p className="subtle">CSV only. Amounts are parsed in each currency’s minor units.</p></div></div><div className="drop-grid"><Dropzone kind="invoices" file={invoices} onFile={setInvoices}/><Dropzone kind="payments" file={payments} onFile={setPayments}/></div><section className="window-settings card" aria-label="Date window settings"><div><strong>Date window</strong><span>Transactions may fall before or after the invoice due date.</span></div><label>Days before due<input aria-label="Days before due" type="number" min="0" value={daysBefore} onChange={event=>setDaysBefore(Number(event.target.value))}/></label><label>Days after due<input aria-label="Days after due" type="number" min="0" value={daysAfter} onChange={event=>setDaysAfter(Number(event.target.value))}/></label></section>{error&&<div className="notice error">{error}</div>}{planLimit&&<UpgradeBanner/>}<div className="run-bar"><div><strong>Deterministic matching</strong><span>No LLM, no invented FX rates.</span></div><button className="button" disabled={!invoices||!payments||busy} onClick={run}><Play size={15}/>{busy?"Running…":"Run match"}</button></div><p className="privacy-line">Statement data is not used for training.</p></main>}
